### ISSUE TITLE
Add support for recurring events

### ISSUE THREAD

**Issue by juho-jaakkola** [arckinteractive/events_api#1]
Currently a piece of metadata tells if event is recurring and how. There's however a need to query them in a decent way.

For example the request "Get all events for January 2015" may include an event that was added in December 2014 but is recurring weekly.

Possible approaches:
- Create duplicate entities for each repeated day, and link them together somehow
- Create queries that can figure it out on the fly?
- Something else?

**Comment by beck24** [comment]
I'm thinking the second option has to be the answer.  Consider a daily repeating event - with option 1 we're creating 365 entities to represent it for the entire year.  Then there's the question of how far into the future do we create them?
It needs to be something calculated I think.
