### ISSUE TITLE
class/subtype suggestion

### ISSUE THREAD

**Issue by Daltonstudio** [arckinteractive/events_api#14]
Just a suggestion.
Would you guys consider using a different subtype and classname than 'Event' to ensure compatibility with Coldtricks 'Event Manager'. I'm playing with both and I changed it to AgendaEvent to make them compatible.
I can imagine that one would want to use both since they serve a different usecase where this one is more an agenda and Coldtricks one handles a more real event like things (slots/fees/rsvp,...)

**Comment by hypeJunction** [comment]
I guess we could change the subtypes to arck_event and arck_calendar

**Comment by Daltonstudio** [comment]
Right, only subtype, I was still playing with the initial version. 
arck_event and arck_calendar would be nice if you're up to it.

**Comment by hypeJunction** [comment]
It's a commissioned project, so we will need to discuss whether we want to sign it with arck_ and if we care at all, as eventually we plan on adding all the other features. You can always change the subtype in your clone.
