### ISSUE TITLE
Missing class vcalendar in Calendar and Event

### ISSUE THREAD

**Issue by mrclay** [arckinteractive/events_api#17]
https://github.com/arckinteractive/events_api/blob/1e63d62754b67892a5ec1a866dd18dba0f89fd76/classes/Events/API/Calendar.php#L401

**Comment by mrclay** [comment]
I see https://github.com/iCalcreator/iCalcreator/blob/master/src/vcalendar.php but it's in a namespace. Maybe older version?

**Comment by mrclay** [comment]
Ahh, our dependency is on the master branch and they've updated.

**Comment by hypeJunction** [comment]
Likely. It's locked to dev-master. Check the SHA in the lock file for GG and maybe update the composer to use that sha until we figure out what has changed.

**Comment by hypeJunction** [comment]
As far as I remember they never had any releases tagged, maybe something has changed
