### ISSUE TITLE
Add support for google calendar

### ISSUE THREAD

**Issue by beck24** [arckinteractive/events_api#3]

**Comment by hypeJunction** [comment]
What needs to be done in terms of Google Calendar integration?
I have added the ical feed, just need to add HMAC or WS tokens to have the feed available from behind the wall.

**Comment by beck24** [comment]
actually I'm not sure exactly what he's expecting in terms of gcal integration.  I imagine the most basic case would be importing events from google calendar.  I haven't looked at the google calendar API, but I imagine it could be possible to sync back as well, so elgg events get pushed to google calendar.
I'll ask Ed for more clarification on his expectations for google calendar

**Comment by beck24** [comment]
According to the spec:
`For example, I want to click the "Add by URL" link in Google calendar to to add dynamic member or group calendar events`

I think the ical feed is enough for that at this point.  Lets not over complicate things for now.

**Comment by hypeJunction** [comment]
Ok, let's close this and open a ticket for tokens
