### ISSUE TITLE
Add support for event types

### ISSUE THREAD

**Issue by juho-jaakkola** [arckinteractive/events_api#4]
Basically this means the ability to:
- Manage event types in admin panel
- Set type for an individual event
- Define styles for each type

I'm not sure whether this should be part of the plugin. I don't want to bloat it.

**Comment by beck24** [comment]
Yeah I'm thinking that would be bloat at this point.  We're tossing around the idea of using a widget-based functionality to enable features on a per-event basis.  That way if an event needs to track attendance there could be a widget for that, or if it needs a map it can be a location widget, etc.  Thoughts on that idea?

**Comment by juho-jaakkola** [comment]
My use case is that the different types would have different background colors in the full calendar view so it would be easier to see how many/often each type is occurring.

**Comment by juho-jaakkola** [comment]
In event_calendar there is a hook `'prepare', 'event_calendar:json'` that asks if anyone wants to alter the event before sending the data. I'm adding classes using that hook.

Is something like that currently possible?

**Comment by beck24** [comment]
oh I see - colors is on my todo list.  The fullcalendar library has out of the box support for listing different colors and I was going to add a color picker for it at some point.
Adding in a hook at the json export is certainly possible and a good idea

**Comment by hypeJunction** [comment]
I am closing this as there is no enough extension points to implement event types as a plugin.
@juho-jaakkola you can now use 'export:instance','events_api' hook
