### ISSUE TITLE
ical view doesn't show results

### ISSUE THREAD

**Issue by beck24** [arckinteractive/events_api#9]
![screen shot 2015-02-24 at 9 34 03 pm](https://cloud.githubusercontent.com/assets/738363/6365465/eca8d968-bc6c-11e4-86a1-aa5f54e2364f.png)
![screen shot 2015-02-24 at 9 34 14 pm](https://cloud.githubusercontent.com/assets/738363/6365466/eca9a9c4-bc6c-11e4-9c10-efb977712a2c.png)

**Comment by hypeJunction** [comment]
Can't reproduce. Could you check again with latest changes?
